eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8084
spring:
  application:
    name: service-feign
  main:
    #允许你重写
    allow-bean-definition-overriding: true
ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    #断向路由器
    enabled: true

